server:
  port: 8004

spring:
  rabbitmq:
    username: djaller
    password: 4l3hA255kX9U
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-server
          predicates:
            - Path=/auth/oauth2/**, /auth/api/**, /.well-known/**

        - id: auth-client
          uri: http://localhost:3000/auth
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: mail-server
          uri: lb://mail-server
          predicates:
            - Path=/api/mail-templates/**, /api/send-mails/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: tontine-server
          uri: lb://tontine-server
          predicates:
            - Path=/api/tontines/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: webhook-server
          uri: lb://webhook-server
          predicates:
            - Path=/api/webhooks/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: core-server
          uri: lb://api-server
          predicates:
            - Path=/api/accounts/**
          filters:
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8004

logging:
  level:
    com.djaller.server: debug
