spring:
  thymeleaf:
    cache: true
  zipkin:
    sender:
      type: rabbit
  application:
    name: auth-server
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app-name: auth-server
springdoc:
  api-docs:
    enabled: true

server:
  forward-headers-strategy: framework

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  oauth2:
    enabled: true
    load-balanced: true
  compression:
    request:
      enabled: true
  client:
    config:
      create-account:
        exception-propagation-policy: UNWRAP
      update-account:
        exception-propagation-policy: UNWRAP

logging:
  level:
    com.djaller.server.auth.feign: DEBUG
