spring:
  thymeleaf:
    cache: true
  zipkin:
    sender:
      type: rabbit
  application:
    name: auth-server
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  #autoconfigure:
   # exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app-name: auth-server
springdoc:
  api-docs:
    enabled: true

server:
  forward-headers-strategy: framework
#  error:
#    whitelabel:
#      enabled: false

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
  client:
    config:
      api-server:
        exception-propagation-policy: UNWRAP

logging:
  level:
    com.djaller.server.auth.feign: DEBUG
