spring:
  zipkin:
    sender:
      type: rabbit
  application:
    name: api-server
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
