spring:
  zipkin:
    sender:
      type: rabbit
  application:
    name: tontine-server
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
