server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  rabbitmq:
    username: djaller
    password: 4l3hA255kX9U
  zipkin:
    sender:
      type: rabbit
