spring:
  rabbitmq:
    username: djaller
    password: 4l3hA255kX9U
  mail:
    host: localhost
    port: 1025
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8004/auth
  jpa:
    show-sql: true
server:
  port: 8002

management:
  health:
    mail:
      enabled: false
