spring:
  zipkin:
    sender:
      type: rabbit
  application:
    name: webhook-server
  cloud:
    function:
      definition: on_app_event
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
